# Import the libreries

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

# Data Preprocessing

Import Dataset

In [ ]:
dataset = pd.read_csv('./Churn_Modelling.csv')

In [ ]:
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [ ]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

# Categorical Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelEncoder = LabelEncoder()

x[:,2] = labelEncoder.fit_transform(x[:,2])
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

# OneHotEncoding

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder() ,[1])],remainder = 'passthrough')

x = np.array(ct.fit_transform(x))
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

# Splitting Data

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2 ,random_state = 0)

# Feature Scalling

In [ ]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

##2.Building ANN

# Initializing ANN

In [ ]:
ann = tf.keras.models.Sequential()
# Sequential(): Initializes a linear stack of layers.
# This means we’ll add layers one after the other, which is a standard approach for feedforward networks.

# Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6 ,activation='relu'))
# Dense(): Adds a fully connected (dense) layer.

# activation='relu': Specifies the activation function used in this layer. The ReLU (Rectified Linear Unit) activation function helps the network learn complex patterns.
# It outputs 0 for negative inputs and the input value for positive inputs


# Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6 ,activation='relu'))

# Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1 ,activation='sigmoid'))
# activation='sigmoid': The sigmoid function squashes the output to a probability between 0 and 1, making it suitable for binary classification.

# 3.Training the ANN

# Compiling the ANN

In [ ]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# optimizer='adam': Adam is an optimization algorithm that adjusts the learning rate during training for faster convergence.
# loss='binary_crossentropy': The loss function used for binary classification problems. It measures the difference between the predicted probability and the actual label (1 or 0).
# metrics=['accuracy']: Specifies accuracy as the metric to monitor during training. It gives an idea of how well the model is performing.

## 4.Training the model

In [ ]:
ann.fit(x_train, y_train, batch_size=32, epochs=100)
# batch_size=32: The number of samples to be processed before updating the model's weights. A smaller batch size uses less memory, while a larger batch size trains faster.
# epochs=100: The number of times the model will iterate over the entire training dataset. Increasing epochs allows the model to learn more, but too many can lead to overfitting.

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7368 - loss: 0.5694
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7915 - loss: 0.4892
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8059 - loss: 0.4586
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8143 - loss: 0.4407
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8161 - loss: 0.4303
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8103 - loss: 0.4250
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8189 - loss: 0.4129
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8207 - loss: 0.4037
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8209 - loss: 0.4021
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8276 - loss: 0.3983
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8195 - loss: 0.4027
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

# Evaluating the Model

In [ ]:
test_loss, test_accuracy = ann.evaluate(x_test, y_test)
print(f'Test Accuracy: {test_accuracy}')
print(f'Test loss: {test_loss}')

# evaluate(): Tests the model on the test data and computes the loss and accuracy. The model has not seen the test data during training,
# so this gives an idea of how well it generalizes to unseen data.

# test_accuracy: Prints the accuracy on the test data, giving a clear measure of how well the model performed on new data.

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8648 - loss: 0.3168
Test Accuracy: 0.8669999837875366
Test loss: 0.32695266604423523


## Making Predictions

In [ ]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
y_pred

# predict(): Runs the model on new data (in this case, the test set). Since we used a sigmoid activation for binary classification,
# the predictions will be probabilities between 0 and 1.

# (y_pred > 0.5): Converts the probabilities into binary predictions (if the probability is greater than 0.5, predict 1; otherwise, predict 0).

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step


array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

# Evaluating Predictions

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:\n', cm)
print('Accuracy Score:', accuracy_score(y_test, y_pred))


Confusion Matrix:
 [[1523   72]
 [ 194  211]]
Accuracy Score: 0.867
